import { v4 as uuid } from "uuid";
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    id:1,
    title: "Feather Wall Macrame",
    price: "1000",
    offprice:700,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655217334/ProjectImages/glass-1_bjdgto.jpg",
    rating:4.5,
    categoryName: "Glass Decor",
  },
  {
    _id: uuid(),
    title: "Wall hanging ",
    price: "700",
    offprice:600,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655217393/ProjectImages/glass-2_hqyrv1.jpg",
    rating:4,
    categoryName: "Glass Decor",
  },
  { 
    _id: uuid(),
    title: "shelf Wall hanging",
    price: "700",
    offprice:600,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655217446/ProjectImages/glass4_j76inr.jpg",
    rating:4.1,
    categoryName: "Glass Decor",
  },
  {
    _id: uuid(),
    title: "Multicolor hanging",
    price: "700",
    offprice:600,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655217447/ProjectImages/glass3_thkdb2.jpg",
    rating:3,
    categoryName: "Glass Decor",
  },
  {
    _id: uuid(),
    title: "Circular macrame",
    price: "700",
    offprice:500,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1647577271/ProjectImages/productmacrame-9_anrjcx.png",
    rating:3.5,
    categoryName: "Glass Decor",
  },
  {
    _id: uuid(),
    title: "Macrame plant hangers",
    price: "700",
    offprice:500,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655217514/ProjectImages/glass5_duisfm.jpg",
    rating:3.5,
    categoryName: "Glass Decor",
  },
  {
    _id: uuid(),
    title: "Triangle macrame",
    price: "700",
    offprice:500,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655217617/ProjectImages/glass6_sgltvh.jpg",
   rating:3.5,
    categoryName: "Glass Decor",
  },
  {
    _id: uuid(),
    title: "dreamcatcher",
    price: "700",
    offprice:500,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655219208/ProjectImages/lightdecor2_yw4nvt.jpg",
    rating:3.5,
    categoryName: "Lights Decor",
  },
  {
    _id: uuid(),
    title: "dreamcatcher",
    price: "500",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655219180/ProjectImages/lightdecor1_rnrcsm.jpg",
    rating:4.5,
    categoryName: "Lights Decor",
  },
  {
    _id: uuid(),
    title: "dreamcatcher",
    price: "500",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655219207/ProjectImages/lightdecor4_piwr4u.jpg",
    rating:4.5,
    categoryName: "Lights Decor",
  },
  {
    _id: uuid(),
    title: "dreamcatcher",
    price: "500",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655219208/ProjectImages/lightdecor5_wdo0rq.jpg",
    rating:4.5,
    categoryName: "Lights Decor",
  },
  {
    _id: uuid(),
    title: "dreamcatcher",
    price: "500",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655219207/ProjectImages/lightdecor3_boohqu.jpg",
    rating:4,
    categoryName: "Lights Decor",
  },
  {
    _id: uuid(),
    title: "dreamcatcher",
    price: "700",
    offprice:300,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655219392/ProjectImages/lightdecor6_n5iwnh.jpg",
    rating:4.5,
    categoryName: "Lights Decor",
  },
  {
    _id: uuid(),
    title: "plants",
    price: "500",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655218064/ProjectImages/walldecor1_fawq6r.jpg",
    rating:3.8,
    categoryName: "Wall Decor",
  },
  {
    _id: uuid(),
    title: "plants",
    price: "500",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655218064/ProjectImages/walldecor6_yv6pap.jpg",
    rating:3.9,
    categoryName: "Wall Decor",
  },
  {
    _id: uuid(),
    title: "plants",
    price: "600",
    offprice:300,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655218064/ProjectImages/walldecor4_zwdoo2.jpg",
    rating:4.1,
    categoryName: "Wall Decor",
  },
  {
    _id: uuid(),
    title: "plants",
    price: "500",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655218064/ProjectImages/walldecor2_gxkg3h.jpg",
    rating:3.8,
    categoryName: "Wall Decor",
  },
  {
    _id: uuid(),
    title: "plants",
    price: "400",
    offprice:200,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655218063/ProjectImages/walldecor5_mmxl38.jpg",
    rating:1,
    categoryName: "Wall Decor",
  },
  {
    _id: uuid(),
    title: "plants",
    price: "1200",
    offprice:600,
    image:"https://res.cloudinary.com/dgomw715r/image/upload/v1655218062/ProjectImages/walldecor3_xc4ntn.jpg",
    rating:4.8,
    categoryName: "Wall Decor",
  },

];
